let object = [
  
    {
        id:1,
        fashion : "  Shirt slim",
        add: "Add To Cart",
        description: " Category : Shirts",
        totalquantity: 20,
        type:"shirt",
        price: 120,
        images:"/images/1.png",
        remove: "Remove from cart",
    },
    {
        id:2,
        fashion : " Adidas Fit Shirt ",
        add: "Add To Cart",
        description: " Category : Shirts",
        totalquantity: 20,
        type:"shirt",
        price:  100,
        images:"/images/2.webp",
        remove: "Remove from cart",
    },
    {
        id:3,
        fashion : " Lacoste Shirt ",
        add: "Add To Cart",
        description: " Category : Shirts",
        totalquantity: 20,
        type:"shirt",
        price: 220,
        images:"/Images/3.png",
        remove: "Remove from cart",
    },
    {
        id:4,
        fashion : " Puma Shirt ",
        add: "Add To Cart",
        description: " Category : Shirts",
        totalquantity: 20,
        type:"shirt",
        price:  420,
        images:"/Images/4.webp",
        remove: "   Remove from cart",
    },
    {
        id:5,
        fashion : " Nike Slim Pant ",
        add: "Add To Cart",
        description: " Category : Pant",
        totalquantity: 20,
        type:"pant",
        price:  820,
        images:"/Images/5.webp",
        remove: "Remove from cart",
    },
    {
        id:6,
        fashion : " Lee Pant ",
        add: "Add To Cart",
        description: " Category : Pant",
        totalquantity: 20,
        type:"pant",
        price:  1020,
        images:"/Images/6.webp",
        remove: "Remove from cart",
    },
]
export default object;